# Generated by Django 2.2.24 on 2025-01-22 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
    ]
